'use client';

import { createContext, useContext, useState } from 'react';

type Language = 'en' | 'te';
const dictionaries = {
  en: { home: 'Home', ponds: 'My Ponds', daily: 'Daily Entry', money: 'Money', more: 'More', quickAdd: 'Quick add', login: 'Sign in', requestOtp: 'Request OTP', verify: 'Verify OTP', mobile: 'Mobile number', code: 'OTP code', submit: 'Submit', loading: 'Loading…', noData: 'No data yet', addEntry: 'Add entry', serverAttention: 'Server-evaluated attention and reasons.', noPonds: 'No ponds found.', backPonds: 'Back to ponds', activeCrop: 'Active crop', noActiveCrop: 'No active crop.', valuesServer: 'Values are validated and calculated by the API.', saved: 'Saved on the server.', sameYesterday: 'Same as yesterday', openActiveCrop: 'Open an active crop first.', feed: 'Feed', growth: 'Growth', water: 'Water', medicine: 'Medicine', health: 'Health', checkTray: 'Check tray', date: 'Date', mealSlot: 'Meal slot', feedItem: 'Feed item', quantityKg: 'Quantity (kg)', sampleDate: 'Sample date', doc: 'DOC', animalsSample: 'Animals in sample', sampleWeight: 'Sample weight (g)', readAt: 'Read at', slot: 'Slot', source: 'Source', ph: 'pH', doMgl: 'DO (mg/L)', temperature: 'Temperature', medicineItem: 'Medicine', quantity: 'Quantity', unit: 'Unit', method: 'Method', reason: 'Reason', costPaise: 'Cost (paise)', eventDate: 'Event date', symptoms: 'Symptoms', mortality: 'Mortality count', labTested: 'Lab tested', trayId: 'Check tray', feedPlaced: 'Feed placed (kg)', verdict: 'Verdict', residualWeight: 'Residual weight (g)', saveEntry: 'Save entry', loadingPonds: 'Loading ponds…', otpSent: 'OTP sent. Check the development API log.', unableSignIn: 'Unable to sign in', chooseBusiness: 'Choose business', businessHint: 'Enter the business ID provided by your administrator.', businessId: 'Business ID', continue: 'Continue', businessFailed: 'Business switch failed', brand: 'AE Farm & Financial Management' },
  te: { home: 'హోమ్', ponds: 'నా చెరువులు', daily: 'రోజువారీ నమోదు', money: 'డబ్బు', more: 'మరిన్ని', quickAdd: 'త్వరగా జోడించు', login: 'సైన్ ఇన్', requestOtp: 'OTP పంపండి', verify: 'ధృవీకరించండి', mobile: 'మొబైల్ నంబర్', code: 'OTP కోడ్', submit: 'సమర్పించు', loading: 'లోడ్ అవుతోంది…', noData: 'డేటా లేదు', addEntry: 'నమోదు జోడించు', serverAttention: 'సర్వర్ గణించిన శ్రద్ధ స్థితి మరియు కారణాలు.', noPonds: 'చెరువులు కనబడలేదు.', backPonds: 'చెరువులకు తిరిగి', activeCrop: 'ప్రస్తుత పంట', noActiveCrop: 'ప్రస్తుత పంట లేదు.', valuesServer: 'విలువలను API ధృవీకరించి లెక్కిస్తుంది.', saved: 'సర్వర్‌లో సేవ్ అయింది.', sameYesterday: 'నిన్నటిలాగే', openActiveCrop: 'ముందుగా ప్రస్తుత పంటను తెరవండి.', feed: 'ఆహారం', growth: 'వృద్ధి', water: 'నీరు', medicine: 'మందు', health: 'ఆరోగ్యం', checkTray: 'చెక్ ట్రే', date: 'తేదీ', mealSlot: 'భోజన సమయం', feedItem: 'ఆహార పదార్థం', quantityKg: 'పరిమాణం (కిలోలు)', sampleDate: 'నమూనా తేదీ', doc: 'DOC', animalsSample: 'నమూనాలో జంతువులు', sampleWeight: 'నమూనా బరువు (గ్రా)', readAt: 'చదివిన సమయం', slot: 'సమయం', source: 'మూలం', ph: 'pH', doMgl: 'DO (mg/L)', temperature: 'ఉష్ణోగ్రత', medicineItem: 'మందు', quantity: 'పరిమాణం', unit: 'యూనిట్', method: 'పద్ధతి', reason: 'కారణం', costPaise: 'ఖర్చు (పైసలు)', eventDate: 'ఈవెంట్ తేదీ', symptoms: 'లక్షణాలు', mortality: 'మరణాల సంఖ్య', labTested: 'ల్యాబ్ పరీక్ష', trayId: 'చెక్ ట్రే', feedPlaced: 'ఉంచిన ఆహారం (కిలోలు)', verdict: 'తీర్పు', residualWeight: 'మిగిలిన బరువు (గ్రా)', saveEntry: 'నమోదు సేవ్ చేయండి', loadingPonds: 'చెరువులు లోడ్ అవుతున్నాయి…', otpSent: 'OTP పంపబడింది. API లాగ్ చూడండి.', unableSignIn: 'సైన్ ఇన్ చేయలేకపోయాము', chooseBusiness: 'వ్యాపారాన్ని ఎంచుకోండి', businessHint: 'నిర్వాహకుడు ఇచ్చిన వ్యాపార ID నమోదు చేయండి.', businessId: 'వ్యాపార ID', continue: 'కొనసాగించు', businessFailed: 'వ్యాపారం మార్చడం విఫలమైంది', brand: 'AE ఫార్మ్ & ఆర్థిక నిర్వహణ' },
} as const;
type Dictionary = { [key in keyof typeof dictionaries.en]: string };
const I18nContext = createContext<{ language: Language; setLanguage: (language: Language) => void; t: Dictionary }>({ language: 'en', setLanguage: () => undefined, t: dictionaries.en });

export function I18nProvider({ children }: Readonly<{ children: React.ReactNode }>) {
  const [language, setLanguage] = useState<Language>('en');
  return <I18nContext.Provider value={{ language, setLanguage, t: dictionaries[language] }}>{children}</I18nContext.Provider>;
}
export function useI18n() { return useContext(I18nContext); }
